test CI workflow

diff --git a/.github/workflows/catalog-service.yml b/.github/workflows/catalog-service.yml
--- a/.github/workflows/catalog-service.yml
+++ b/.github/workflows/catalog-service.yml
@@ -28,8 +28,14 @@ jobs:
           distribution: 'temurin'
           cache: 'maven'
 
+      - name: Debug mvnw file
+        run: |
+          ls -l
+          file mvnw || echo "No mvnw found"
+          head -n 1 mvnw || echo "Can't read mvnw"
+
       - name: Make mvnw executable
-        run: chmod +x ./mvnw
+        run: chmod +x mvnw
 
       - name: Build with Maven
         run: ./mvnw -ntp verify
